import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import LandingPageCategories from "./components/categories/landing-page-categories";
import NavBar from "./components/nav-bar/nav-bar";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Shopper</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="landing-page">
        <NavBar />
        <LandingPageCategories />
        <div className="dealofweek">dealofweek</div>
        <div className="popularservices">popularservices</div>
        <div className="offers">limitedoffers</div>
        <div className="shopbycat">shopby</div>
      </div>
    </div>
  );
}
